# Generated by Django 2.2.11 on 2020-03-26 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('ip_address', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('time_out', models.DateTimeField(default=datetime.datetime(2020, 3, 27, 18, 2, 59, 438143))),
                ('time_in', models.DateTimeField(auto_now=True)),
                ('attemps', models.IntegerField()),
            ],
        ),
    ]
